
[profile.contracts]
src = 'apps/contracts/src'
test = 'apps/contracts/tests'
out = 'apps/contracts/dist'
cache_path = 'apps/contracts/cache'
libs = ['libs', 'node_modules']
solc = '0.8.17'

[profile.contracts-ci]
src = 'apps/contracts/src'
test = 'apps/contracts/tests'
out = 'apps/contracts/dist'
cache_path = 'apps/contracts/cache'
libs = ['libs', 'node_modules']

solc = '0.8.17'
verbosity = 4

[profile.contracts-ci.fuzz]
runs = 1024
max_test_rejects = 924288
