
[profile.default]
    src = 'smart-contracts'
    test = 'smart-contracts/tests'
    out = 'dist/smart-contracts/'
    cache_path = 'smart-contracts/cache/smart-contracts'
    libs = ['smart-contracts/libs', 'node_modules']
    solc = "0.8.17"

[profile.ci]
    src = 'src/smart-contracts'
    test = 'smart-contracts/tests'
    out = 'dist/smart-contracts/'
    cache_path = 'smart-contracts/cache/smart-contracts'
    libs = ['smart-contracts/libs', 'node_modules']
    solc = "0.8.17"
    verbosity = 4

[profile.ci.fuzz]
    runs = 1024
    max_test_rejects = 924288

