
[profile.default]
src = './src'
test = './tests'
out = './dist'
cache_path = './cache'
libs = ['../../libs', '../../node_modules']
solc = '0.8.17'

[profile.ci]
src = './src'
test = './tests'
out = './dist'
cache_path = './cache'
libs = ['../../libs', '../../node_modules']
solc = '0.8.17'
verbosity = 4

[profile.ci.fuzz]
runs = 1024
max_test_rejects = 924288
