name: Preview

on:
  push:
    branches-ignore:
      - main

env:
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  format-test-lint:
    uses: Byont-Ventures/website/.github/workflows/format-test-lint.yml@main
    secrets: inherit

  deploy:
    uses: Byont-Ventures/website/.github/workflows/vercel.yml@main
    with:
      VERCEL_ENVIRONMENT: preview
    secrets: inherit
