name: Vercel Deployment Workflow

on:
  workflow_call:
    inputs:
      VERCEL_ENVIRONMENT:
        required: true
        type: string
    secrets:
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true
      VERCEL_TOKEN:
        required: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  vercel:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.VERCEL_ENVIRONMENT }}
      url: ${{ steps.vercel_deploy.outputs.url_output }}

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Vercel CLI
        run: yarn global add vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ inputs.VERCEL_ENVIRONMENT }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: vercel_deploy
        run: echo "url_output=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
